2021-11-15 17:19:56,584 DEBUG server.py Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2021-11-15 17:19:56,586 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2021-11-15 17:19:56,587 DEBUG server.py Аргументы успешно загружены.
2021-11-15 17:19:56,588 DEBUG server.py Была вызвана функция arg_parser c параметрами ('7777', ''), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2021-11-15 17:19:56,817 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2021-11-15 17:21:29,297 INFO core.py Установлено соедение с ПК ('127.0.0.1', 51626)
2021-11-15 17:21:29,803 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1380, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51626)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:21:29,803 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1636986089.326341, 'user': {'account_name': '1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArXDW/5Ngh/gdnlIQRpOt\nB5kjmWDQpIVN0v0H3XKyb68zAdOxDNtCL9NkxzGgRb0kUrr/QADkcyKoTDSDiEjj\n3k9YEV383CAhg+Y2r3J8kELWcLD4o1NOi5l7nPT4YfRyiotBvlYUW3iNY5bp2vKw\nifjsM+hgrHAr+XwND3TDVgFKYkxO7POFA8lYYeioV1Jqe23FLXSUAWlpJTWqetCm\nMfuoMscHEklKlW+rizmuZvahdhJA2FPst95SrnzmWv+I2H9m2YrYbHnf8v1IURCj\nxuZzg7OUUkVR3B77OveQtsLDe6BaJyvIsEIIRM5TyChodFBDZYf9uGSbvTYcwHdw\n7QIDAQAB\n-----END PUBLIC KEY-----'}}
2021-11-15 17:21:29,803 DEBUG core.py Start auth process for {'account_name': '1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArXDW/5Ngh/gdnlIQRpOt\nB5kjmWDQpIVN0v0H3XKyb68zAdOxDNtCL9NkxzGgRb0kUrr/QADkcyKoTDSDiEjj\n3k9YEV383CAhg+Y2r3J8kELWcLD4o1NOi5l7nPT4YfRyiotBvlYUW3iNY5bp2vKw\nifjsM+hgrHAr+XwND3TDVgFKYkxO7POFA8lYYeioV1Jqe23FLXSUAWlpJTWqetCm\nMfuoMscHEklKlW+rizmuZvahdhJA2FPst95SrnzmWv+I2H9m2YrYbHnf8v1IURCj\nxuZzg7OUUkVR3B77OveQtsLDe6BaJyvIsEIIRM5TyChodFBDZYf9uGSbvTYcwHdw\n7QIDAQAB\n-----END PUBLIC KEY-----'}
2021-11-15 17:21:29,832 DEBUG core.py Unknown username, sending {'response': 400, 'error': 'Пользователь не зарегистрирован.'}
2021-11-15 17:21:29,834 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1380, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51626)>, {'response': 400, 'error': 'Пользователь не зарегистрирован.'}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:23:20,936 INFO core.py Установлено соедение с ПК ('127.0.0.1', 51627)
2021-11-15 17:23:21,440 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1336, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51627)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:23:21,440 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1636986200.9524457, 'user': {'account_name': 'testo', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr8tfBtTNQeCe4Vcro9jI\nG0WSMeI5D9Zn51A+cI3FEnxTq4ecs8nLri3eQHKZ6+dyzx+RdfF87e/hyHLyZOJf\nvrHUzOOfIH0ScwK7OmpG0JrpUo7F+9cfzj8JEBk96LZgvOWQGisNvyr17TvCVOuB\nkj3hE4GYvNhUPMrHLrcISZQO2Ahy77YMcl70p0xTlTWx0ysh0zyKDXN17scfn2lD\nqE6YP5tOqUcPgYmNTe0cDJQj7gmODxYchSRnZyD+J0J/mVeeaH9gLJmylgjbblMS\nlSUyda9d+Eajj06MLYGIBZKIjrg/SqHelKXTq7G8sSleO1AbhYXw3P4SGvuFNYC1\nNwIDAQAB\n-----END PUBLIC KEY-----'}}
2021-11-15 17:23:21,440 DEBUG core.py Start auth process for {'account_name': 'testo', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr8tfBtTNQeCe4Vcro9jI\nG0WSMeI5D9Zn51A+cI3FEnxTq4ecs8nLri3eQHKZ6+dyzx+RdfF87e/hyHLyZOJf\nvrHUzOOfIH0ScwK7OmpG0JrpUo7F+9cfzj8JEBk96LZgvOWQGisNvyr17TvCVOuB\nkj3hE4GYvNhUPMrHLrcISZQO2Ahy77YMcl70p0xTlTWx0ysh0zyKDXN17scfn2lD\nqE6YP5tOqUcPgYmNTe0cDJQj7gmODxYchSRnZyD+J0J/mVeeaH9gLJmylgjbblMS\nlSUyda9d+Eajj06MLYGIBZKIjrg/SqHelKXTq7G8sSleO1AbhYXw3P4SGvuFNYC1\nNwIDAQAB\n-----END PUBLIC KEY-----'}
2021-11-15 17:23:21,443 DEBUG core.py Correct username, starting passwd check.
2021-11-15 17:23:21,449 DEBUG core.py Auth message = {'response': 511, 'bin': '02199072f4b7de6574460c6f00d276ae3732e42c1d606475cb11d26bb18d2ab280b471a1b2b4172364e947dfc32932aafa7b5d228d6e3f661da6bf9784464b77'}
2021-11-15 17:23:21,454 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1336, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51627)>, {'response': 511, 'bin': '02199072f4b7de6574460c6f00d276ae3732e42c1d606475cb11d26bb18d2ab280b471a1b2b4172364e947dfc32932aafa7b5d228d6e3f661da6bf9784464b77'}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:23:21,458 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1336, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51627)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:23:21,461 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1336, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51627)>, {'response': 200}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:23:22,094 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1336, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51627)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:23:22,094 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1636986201.461392, 'account_name': 'testo'}
2021-11-15 17:23:22,099 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1336, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51627)>, {'response': 202, 'data_list': ['test1', 'test2', 'test3', 'Radif', 'Lui', 'testo']}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2021-11-15 17:23:22,603 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1336, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51627)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:23:22,603 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1636986202.2283762, 'user': 'testo'}
2021-11-15 17:23:22,617 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1336, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51627)>, {'response': 202, 'data_list': []}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2021-11-15 17:23:42,746 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1336, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51627)>, {'response': 205}), {}. Вызов из модуля common.utils.Вызов из функции main().Вызов из функции service_update_lists
2021-11-15 17:23:43,646 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1336, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51627)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:23:43,646 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1636986223.1694489, 'account_name': 'testo'}
2021-11-15 17:23:43,649 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1336, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51627)>, {'response': 202, 'data_list': ['test1', 'test2', 'test3', 'Radif', 'Lui', 'testo', 'testo2']}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2021-11-15 17:23:44,152 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1336, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51627)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:23:44,152 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1636986223.805203, 'user': 'testo'}
2021-11-15 17:23:44,163 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1336, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51627)>, {'response': 202, 'data_list': []}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2021-11-15 17:24:48,229 INFO core.py Установлено соедение с ПК ('127.0.0.1', 59306)
2021-11-15 17:24:48,733 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=2016, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59306)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:24:48,733 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1636986288.2438533, 'user': {'account_name': 'testo2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsXAscVbw1yG/qLciWUtG\nAdGDDZjJVxtu/awf+slJwN7Kqag11MYX2kQ+loaGIwHyWaygFZtm1PhdaunnhFRx\nHV4kuJmnwIUTrygnZ+RnmuJtitGqzH7eKSRTFwNZqVvZgikLzafz4bsSKIj7S7vr\nlh3/P3m0gNTOjBreY7lFehdeOz0T7EmCODC85syOGnF6p1dQaM9xwQMjec9httfh\nrotTnGBQy17NJhxR6SlovAaJ6EDdLtbfp0v47FpIYe4vU/FEZCxI+t74kuubGVET\neG8vdkylNJR22mgehaGxvJrHJklTHEoWsjkA5bFkkXy/bS3FXGHpnH1z5yD6dZLJ\nLQIDAQAB\n-----END PUBLIC KEY-----'}}
2021-11-15 17:24:48,733 DEBUG core.py Start auth process for {'account_name': 'testo2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsXAscVbw1yG/qLciWUtG\nAdGDDZjJVxtu/awf+slJwN7Kqag11MYX2kQ+loaGIwHyWaygFZtm1PhdaunnhFRx\nHV4kuJmnwIUTrygnZ+RnmuJtitGqzH7eKSRTFwNZqVvZgikLzafz4bsSKIj7S7vr\nlh3/P3m0gNTOjBreY7lFehdeOz0T7EmCODC85syOGnF6p1dQaM9xwQMjec9httfh\nrotTnGBQy17NJhxR6SlovAaJ6EDdLtbfp0v47FpIYe4vU/FEZCxI+t74kuubGVET\neG8vdkylNJR22mgehaGxvJrHJklTHEoWsjkA5bFkkXy/bS3FXGHpnH1z5yD6dZLJ\nLQIDAQAB\n-----END PUBLIC KEY-----'}
2021-11-15 17:24:48,736 DEBUG core.py Correct username, starting passwd check.
2021-11-15 17:24:48,739 DEBUG core.py Auth message = {'response': 511, 'bin': '64b70657b91adf5425834354d89ba95267bd48955d6e885ca4238565eb58ba11d36fbb9fa016d7b0976345708a2b66e1492a0eb6b5bc7e14bd683f8f3ffb5706'}
2021-11-15 17:24:48,744 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=2016, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59306)>, {'response': 511, 'bin': '64b70657b91adf5425834354d89ba95267bd48955d6e885ca4238565eb58ba11d36fbb9fa016d7b0976345708a2b66e1492a0eb6b5bc7e14bd683f8f3ffb5706'}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:24:48,749 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=2016, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59306)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:24:48,753 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=2016, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59306)>, {'response': 400, 'error': 'Неверный пароль.'}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:40:13,849 DEBUG server.py Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2021-11-15 17:40:13,849 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2021-11-15 17:40:13,851 DEBUG server.py Аргументы успешно загружены.
2021-11-15 17:40:13,852 DEBUG server.py Была вызвана функция arg_parser c параметрами ('7777', ''), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2021-11-15 17:40:14,431 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2021-11-15 17:41:29,142 INFO core.py Установлено соедение с ПК ('127.0.0.1', 64922)
2021-11-15 17:41:29,648 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1320, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64922)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:41:29,649 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1636987289.1589837, 'user': {'account_name': 'testo', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr8tfBtTNQeCe4Vcro9jI\nG0WSMeI5D9Zn51A+cI3FEnxTq4ecs8nLri3eQHKZ6+dyzx+RdfF87e/hyHLyZOJf\nvrHUzOOfIH0ScwK7OmpG0JrpUo7F+9cfzj8JEBk96LZgvOWQGisNvyr17TvCVOuB\nkj3hE4GYvNhUPMrHLrcISZQO2Ahy77YMcl70p0xTlTWx0ysh0zyKDXN17scfn2lD\nqE6YP5tOqUcPgYmNTe0cDJQj7gmODxYchSRnZyD+J0J/mVeeaH9gLJmylgjbblMS\nlSUyda9d+Eajj06MLYGIBZKIjrg/SqHelKXTq7G8sSleO1AbhYXw3P4SGvuFNYC1\nNwIDAQAB\n-----END PUBLIC KEY-----'}}
2021-11-15 17:41:29,649 DEBUG core.py Start auth process for {'account_name': 'testo', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr8tfBtTNQeCe4Vcro9jI\nG0WSMeI5D9Zn51A+cI3FEnxTq4ecs8nLri3eQHKZ6+dyzx+RdfF87e/hyHLyZOJf\nvrHUzOOfIH0ScwK7OmpG0JrpUo7F+9cfzj8JEBk96LZgvOWQGisNvyr17TvCVOuB\nkj3hE4GYvNhUPMrHLrcISZQO2Ahy77YMcl70p0xTlTWx0ysh0zyKDXN17scfn2lD\nqE6YP5tOqUcPgYmNTe0cDJQj7gmODxYchSRnZyD+J0J/mVeeaH9gLJmylgjbblMS\nlSUyda9d+Eajj06MLYGIBZKIjrg/SqHelKXTq7G8sSleO1AbhYXw3P4SGvuFNYC1\nNwIDAQAB\n-----END PUBLIC KEY-----'}
2021-11-15 17:41:29,684 DEBUG core.py Correct username, starting passwd check.
2021-11-15 17:41:29,686 DEBUG core.py Auth message = {'response': 511, 'bin': 'b8115aae0f58ce4d5cb6d80ae67dd073737425642efbef75b488d8995cbac98e8f8907b0f14fd952ef170fb1e736f063be4c1d1f4dd4c83180afd11022636d9d'}
2021-11-15 17:41:29,688 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1320, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64922)>, {'response': 511, 'bin': 'b8115aae0f58ce4d5cb6d80ae67dd073737425642efbef75b488d8995cbac98e8f8907b0f14fd952ef170fb1e736f063be4c1d1f4dd4c83180afd11022636d9d'}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:41:29,689 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1320, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64922)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:41:29,691 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1320, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64922)>, {'response': 200}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:41:30,475 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1320, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64922)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:41:30,475 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1636987289.6919093, 'account_name': 'testo'}
2021-11-15 17:41:30,485 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1320, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64922)>, {'response': 202, 'data_list': ['test1', 'test2', 'test3', 'Radif', 'Lui', 'testo', 'testo2']}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2021-11-15 17:41:30,990 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1320, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64922)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:41:30,990 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1636987290.687995, 'user': 'testo'}
2021-11-15 17:41:31,005 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1320, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64922)>, {'response': 202, 'data_list': []}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2021-11-15 17:42:23,911 INFO core.py Установлено соедение с ПК ('127.0.0.1', 64925)
2021-11-15 17:42:24,415 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1064, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64925)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:42:24,415 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1636987343.9252543, 'user': {'account_name': 'testo2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsXAscVbw1yG/qLciWUtG\nAdGDDZjJVxtu/awf+slJwN7Kqag11MYX2kQ+loaGIwHyWaygFZtm1PhdaunnhFRx\nHV4kuJmnwIUTrygnZ+RnmuJtitGqzH7eKSRTFwNZqVvZgikLzafz4bsSKIj7S7vr\nlh3/P3m0gNTOjBreY7lFehdeOz0T7EmCODC85syOGnF6p1dQaM9xwQMjec9httfh\nrotTnGBQy17NJhxR6SlovAaJ6EDdLtbfp0v47FpIYe4vU/FEZCxI+t74kuubGVET\neG8vdkylNJR22mgehaGxvJrHJklTHEoWsjkA5bFkkXy/bS3FXGHpnH1z5yD6dZLJ\nLQIDAQAB\n-----END PUBLIC KEY-----'}}
2021-11-15 17:42:24,415 DEBUG core.py Start auth process for {'account_name': 'testo2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsXAscVbw1yG/qLciWUtG\nAdGDDZjJVxtu/awf+slJwN7Kqag11MYX2kQ+loaGIwHyWaygFZtm1PhdaunnhFRx\nHV4kuJmnwIUTrygnZ+RnmuJtitGqzH7eKSRTFwNZqVvZgikLzafz4bsSKIj7S7vr\nlh3/P3m0gNTOjBreY7lFehdeOz0T7EmCODC85syOGnF6p1dQaM9xwQMjec9httfh\nrotTnGBQy17NJhxR6SlovAaJ6EDdLtbfp0v47FpIYe4vU/FEZCxI+t74kuubGVET\neG8vdkylNJR22mgehaGxvJrHJklTHEoWsjkA5bFkkXy/bS3FXGHpnH1z5yD6dZLJ\nLQIDAQAB\n-----END PUBLIC KEY-----'}
2021-11-15 17:42:24,418 DEBUG core.py Correct username, starting passwd check.
2021-11-15 17:42:24,420 DEBUG core.py Auth message = {'response': 511, 'bin': 'b9c47eaa4550611693ca806777999db4b540a1953d523a3be78cea01da4a9e325507e7d1d2d635ac413c34c50f246bd7a06218453cafbd169bdc71b53271e34d'}
2021-11-15 17:42:24,426 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1064, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64925)>, {'response': 511, 'bin': 'b9c47eaa4550611693ca806777999db4b540a1953d523a3be78cea01da4a9e325507e7d1d2d635ac413c34c50f246bd7a06218453cafbd169bdc71b53271e34d'}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:42:24,431 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1064, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64925)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:42:24,435 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1064, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64925)>, {'response': 200}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:42:35,970 DEBUG server.py Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2021-11-15 17:42:35,971 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2021-11-15 17:42:35,972 DEBUG server.py Аргументы успешно загружены.
2021-11-15 17:42:35,973 DEBUG server.py Была вызвана функция arg_parser c параметрами ('7777', ''), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2021-11-15 17:42:36,146 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2021-11-15 17:42:50,246 INFO core.py Установлено соедение с ПК ('127.0.0.1', 64927)
2021-11-15 17:42:50,751 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1188, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64927)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:42:50,751 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1636987370.261495, 'user': {'account_name': 'testo', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr8tfBtTNQeCe4Vcro9jI\nG0WSMeI5D9Zn51A+cI3FEnxTq4ecs8nLri3eQHKZ6+dyzx+RdfF87e/hyHLyZOJf\nvrHUzOOfIH0ScwK7OmpG0JrpUo7F+9cfzj8JEBk96LZgvOWQGisNvyr17TvCVOuB\nkj3hE4GYvNhUPMrHLrcISZQO2Ahy77YMcl70p0xTlTWx0ysh0zyKDXN17scfn2lD\nqE6YP5tOqUcPgYmNTe0cDJQj7gmODxYchSRnZyD+J0J/mVeeaH9gLJmylgjbblMS\nlSUyda9d+Eajj06MLYGIBZKIjrg/SqHelKXTq7G8sSleO1AbhYXw3P4SGvuFNYC1\nNwIDAQAB\n-----END PUBLIC KEY-----'}}
2021-11-15 17:42:50,752 DEBUG core.py Start auth process for {'account_name': 'testo', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr8tfBtTNQeCe4Vcro9jI\nG0WSMeI5D9Zn51A+cI3FEnxTq4ecs8nLri3eQHKZ6+dyzx+RdfF87e/hyHLyZOJf\nvrHUzOOfIH0ScwK7OmpG0JrpUo7F+9cfzj8JEBk96LZgvOWQGisNvyr17TvCVOuB\nkj3hE4GYvNhUPMrHLrcISZQO2Ahy77YMcl70p0xTlTWx0ysh0zyKDXN17scfn2lD\nqE6YP5tOqUcPgYmNTe0cDJQj7gmODxYchSRnZyD+J0J/mVeeaH9gLJmylgjbblMS\nlSUyda9d+Eajj06MLYGIBZKIjrg/SqHelKXTq7G8sSleO1AbhYXw3P4SGvuFNYC1\nNwIDAQAB\n-----END PUBLIC KEY-----'}
2021-11-15 17:42:50,783 DEBUG core.py Correct username, starting passwd check.
2021-11-15 17:42:50,785 DEBUG core.py Auth message = {'response': 511, 'bin': '67200a4e9db74b6c76c06ff761cf240b95d7828e32fb260afa98ed051bc9a0a60bcb0e05c88b579357492164d9bd14b24d26560c986989fec7642bb1ec077768'}
2021-11-15 17:42:50,788 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1188, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64927)>, {'response': 511, 'bin': '67200a4e9db74b6c76c06ff761cf240b95d7828e32fb260afa98ed051bc9a0a60bcb0e05c88b579357492164d9bd14b24d26560c986989fec7642bb1ec077768'}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:42:50,791 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1188, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64927)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:42:50,793 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1188, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64927)>, {'response': 200}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:42:51,433 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1188, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64927)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:42:51,434 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1636987370.793504, 'account_name': 'testo'}
2021-11-15 17:42:51,443 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1188, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64927)>, {'response': 202, 'data_list': ['test1', 'test2', 'test3', 'Radif', 'Lui', 'testo', 'testo2']}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2021-11-15 17:42:51,948 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1188, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64927)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:42:51,949 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1636987371.563928, 'user': 'testo'}
2021-11-15 17:42:51,962 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1188, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64927)>, {'response': 202, 'data_list': []}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2021-11-15 17:43:02,629 INFO core.py Установлено соедение с ПК ('127.0.0.1', 64928)
2021-11-15 17:43:03,131 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1168, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64928)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:43:03,131 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1636987382.656467, 'user': {'account_name': 'testo2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsXAscVbw1yG/qLciWUtG\nAdGDDZjJVxtu/awf+slJwN7Kqag11MYX2kQ+loaGIwHyWaygFZtm1PhdaunnhFRx\nHV4kuJmnwIUTrygnZ+RnmuJtitGqzH7eKSRTFwNZqVvZgikLzafz4bsSKIj7S7vr\nlh3/P3m0gNTOjBreY7lFehdeOz0T7EmCODC85syOGnF6p1dQaM9xwQMjec9httfh\nrotTnGBQy17NJhxR6SlovAaJ6EDdLtbfp0v47FpIYe4vU/FEZCxI+t74kuubGVET\neG8vdkylNJR22mgehaGxvJrHJklTHEoWsjkA5bFkkXy/bS3FXGHpnH1z5yD6dZLJ\nLQIDAQAB\n-----END PUBLIC KEY-----'}}
2021-11-15 17:43:03,131 DEBUG core.py Start auth process for {'account_name': 'testo2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsXAscVbw1yG/qLciWUtG\nAdGDDZjJVxtu/awf+slJwN7Kqag11MYX2kQ+loaGIwHyWaygFZtm1PhdaunnhFRx\nHV4kuJmnwIUTrygnZ+RnmuJtitGqzH7eKSRTFwNZqVvZgikLzafz4bsSKIj7S7vr\nlh3/P3m0gNTOjBreY7lFehdeOz0T7EmCODC85syOGnF6p1dQaM9xwQMjec9httfh\nrotTnGBQy17NJhxR6SlovAaJ6EDdLtbfp0v47FpIYe4vU/FEZCxI+t74kuubGVET\neG8vdkylNJR22mgehaGxvJrHJklTHEoWsjkA5bFkkXy/bS3FXGHpnH1z5yD6dZLJ\nLQIDAQAB\n-----END PUBLIC KEY-----'}
2021-11-15 17:43:03,133 DEBUG core.py Correct username, starting passwd check.
2021-11-15 17:43:03,135 DEBUG core.py Auth message = {'response': 511, 'bin': '5e8a534b5777bb67bfad08ba06846934c251caa09d26d27593ba64274a7b2ccbc17455a27775ae8e4ae727e154ab50f4926cea61f0dca5b111b8a60a1351dad6'}
2021-11-15 17:43:03,137 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1168, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64928)>, {'response': 511, 'bin': '5e8a534b5777bb67bfad08ba06846934c251caa09d26d27593ba64274a7b2ccbc17455a27775ae8e4ae727e154ab50f4926cea61f0dca5b111b8a60a1351dad6'}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:43:03,139 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1168, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64928)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:43:03,141 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1168, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64928)>, {'response': 200}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:43:37,784 DEBUG server.py Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2021-11-15 17:43:37,784 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2021-11-15 17:43:37,785 DEBUG server.py Аргументы успешно загружены.
2021-11-15 17:43:37,786 DEBUG server.py Была вызвана функция arg_parser c параметрами ('7777', ''), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2021-11-15 17:43:38,113 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2021-11-15 17:51:47,261 INFO core.py Установлено соедение с ПК ('127.0.0.1', 60325)
2021-11-15 17:51:47,766 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1524, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60325)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:51:47,766 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1636987907.2780867, 'user': {'account_name': 'testo', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr8tfBtTNQeCe4Vcro9jI\nG0WSMeI5D9Zn51A+cI3FEnxTq4ecs8nLri3eQHKZ6+dyzx+RdfF87e/hyHLyZOJf\nvrHUzOOfIH0ScwK7OmpG0JrpUo7F+9cfzj8JEBk96LZgvOWQGisNvyr17TvCVOuB\nkj3hE4GYvNhUPMrHLrcISZQO2Ahy77YMcl70p0xTlTWx0ysh0zyKDXN17scfn2lD\nqE6YP5tOqUcPgYmNTe0cDJQj7gmODxYchSRnZyD+J0J/mVeeaH9gLJmylgjbblMS\nlSUyda9d+Eajj06MLYGIBZKIjrg/SqHelKXTq7G8sSleO1AbhYXw3P4SGvuFNYC1\nNwIDAQAB\n-----END PUBLIC KEY-----'}}
2021-11-15 17:51:47,767 DEBUG core.py Start auth process for {'account_name': 'testo', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr8tfBtTNQeCe4Vcro9jI\nG0WSMeI5D9Zn51A+cI3FEnxTq4ecs8nLri3eQHKZ6+dyzx+RdfF87e/hyHLyZOJf\nvrHUzOOfIH0ScwK7OmpG0JrpUo7F+9cfzj8JEBk96LZgvOWQGisNvyr17TvCVOuB\nkj3hE4GYvNhUPMrHLrcISZQO2Ahy77YMcl70p0xTlTWx0ysh0zyKDXN17scfn2lD\nqE6YP5tOqUcPgYmNTe0cDJQj7gmODxYchSRnZyD+J0J/mVeeaH9gLJmylgjbblMS\nlSUyda9d+Eajj06MLYGIBZKIjrg/SqHelKXTq7G8sSleO1AbhYXw3P4SGvuFNYC1\nNwIDAQAB\n-----END PUBLIC KEY-----'}
2021-11-15 17:51:47,780 DEBUG core.py Correct username, starting passwd check.
2021-11-15 17:51:47,784 DEBUG core.py Auth message = {'response': 511, 'bin': '0507b7413cd59adf2e41ee2684a183c1baaf6a040022edd46ae2bf063f4a23245d1d786ccd6ce0c2ceb40aae250ea82ec5bb6cbafcf369ceffe5b9cd9cd648a6'}
2021-11-15 17:51:47,789 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1524, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60325)>, {'response': 511, 'bin': '0507b7413cd59adf2e41ee2684a183c1baaf6a040022edd46ae2bf063f4a23245d1d786ccd6ce0c2ceb40aae250ea82ec5bb6cbafcf369ceffe5b9cd9cd648a6'}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:51:47,796 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1524, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60325)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:51:47,799 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1524, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60325)>, {'response': 200}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:51:48,502 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1524, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60325)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:51:48,503 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1636987907.800177, 'account_name': 'testo'}
2021-11-15 17:51:48,509 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1524, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60325)>, {'response': 202, 'data_list': ['test1', 'test2', 'test3', 'Radif', 'Lui', 'testo', 'testo2']}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2021-11-15 17:51:49,012 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1524, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60325)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:51:49,012 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1636987908.794081, 'user': 'testo'}
2021-11-15 17:51:49,021 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1524, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60325)>, {'response': 202, 'data_list': []}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2021-11-15 17:53:29,133 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1524, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60325)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:53:29,133 DEBUG core.py Разбор сообщения от клиента : {'action': 'add', 'time': 1636988008.8367743, 'user': 'testo', 'account_name': 'testo2'}
2021-11-15 17:53:50,862 DEBUG server.py Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2021-11-15 17:53:50,862 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2021-11-15 17:53:50,863 DEBUG server.py Аргументы успешно загружены.
2021-11-15 17:53:50,864 DEBUG server.py Была вызвана функция arg_parser c параметрами ('7777', ''), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2021-11-15 17:53:51,094 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2021-11-15 17:54:01,580 INFO core.py Установлено соедение с ПК ('127.0.0.1', 52531)
2021-11-15 17:54:02,085 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1428, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52531)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:54:02,085 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1636988041.609666, 'user': {'account_name': 'testo', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr8tfBtTNQeCe4Vcro9jI\nG0WSMeI5D9Zn51A+cI3FEnxTq4ecs8nLri3eQHKZ6+dyzx+RdfF87e/hyHLyZOJf\nvrHUzOOfIH0ScwK7OmpG0JrpUo7F+9cfzj8JEBk96LZgvOWQGisNvyr17TvCVOuB\nkj3hE4GYvNhUPMrHLrcISZQO2Ahy77YMcl70p0xTlTWx0ysh0zyKDXN17scfn2lD\nqE6YP5tOqUcPgYmNTe0cDJQj7gmODxYchSRnZyD+J0J/mVeeaH9gLJmylgjbblMS\nlSUyda9d+Eajj06MLYGIBZKIjrg/SqHelKXTq7G8sSleO1AbhYXw3P4SGvuFNYC1\nNwIDAQAB\n-----END PUBLIC KEY-----'}}
2021-11-15 17:54:02,085 DEBUG core.py Start auth process for {'account_name': 'testo', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr8tfBtTNQeCe4Vcro9jI\nG0WSMeI5D9Zn51A+cI3FEnxTq4ecs8nLri3eQHKZ6+dyzx+RdfF87e/hyHLyZOJf\nvrHUzOOfIH0ScwK7OmpG0JrpUo7F+9cfzj8JEBk96LZgvOWQGisNvyr17TvCVOuB\nkj3hE4GYvNhUPMrHLrcISZQO2Ahy77YMcl70p0xTlTWx0ysh0zyKDXN17scfn2lD\nqE6YP5tOqUcPgYmNTe0cDJQj7gmODxYchSRnZyD+J0J/mVeeaH9gLJmylgjbblMS\nlSUyda9d+Eajj06MLYGIBZKIjrg/SqHelKXTq7G8sSleO1AbhYXw3P4SGvuFNYC1\nNwIDAQAB\n-----END PUBLIC KEY-----'}
2021-11-15 17:54:02,108 DEBUG core.py Correct username, starting passwd check.
2021-11-15 17:54:02,110 DEBUG core.py Auth message = {'response': 511, 'bin': 'b5a0b3f41cbf8a8b951d01e4d12ddc4deef0503510c39f7876ed499d21ebcb897dd5e16f27f0405110de944f2907f5adcf6f2bbcfb8fbb818c7a62cb90af100c'}
2021-11-15 17:54:02,113 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1428, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52531)>, {'response': 511, 'bin': 'b5a0b3f41cbf8a8b951d01e4d12ddc4deef0503510c39f7876ed499d21ebcb897dd5e16f27f0405110de944f2907f5adcf6f2bbcfb8fbb818c7a62cb90af100c'}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:54:02,114 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1428, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52531)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:54:02,116 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1428, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52531)>, {'response': 200}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:54:09,604 DEBUG server.py Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2021-11-15 17:54:09,604 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2021-11-15 17:54:09,605 DEBUG server.py Аргументы успешно загружены.
2021-11-15 17:54:09,606 DEBUG server.py Была вызвана функция arg_parser c параметрами ('7777', ''), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2021-11-15 17:54:09,760 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2021-11-15 17:54:17,362 INFO core.py Установлено соедение с ПК ('127.0.0.1', 52534)
2021-11-15 17:54:17,865 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1372, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52534)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:54:17,865 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1636988057.39273, 'user': {'account_name': 'testo', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr8tfBtTNQeCe4Vcro9jI\nG0WSMeI5D9Zn51A+cI3FEnxTq4ecs8nLri3eQHKZ6+dyzx+RdfF87e/hyHLyZOJf\nvrHUzOOfIH0ScwK7OmpG0JrpUo7F+9cfzj8JEBk96LZgvOWQGisNvyr17TvCVOuB\nkj3hE4GYvNhUPMrHLrcISZQO2Ahy77YMcl70p0xTlTWx0ysh0zyKDXN17scfn2lD\nqE6YP5tOqUcPgYmNTe0cDJQj7gmODxYchSRnZyD+J0J/mVeeaH9gLJmylgjbblMS\nlSUyda9d+Eajj06MLYGIBZKIjrg/SqHelKXTq7G8sSleO1AbhYXw3P4SGvuFNYC1\nNwIDAQAB\n-----END PUBLIC KEY-----'}}
2021-11-15 17:54:17,865 DEBUG core.py Start auth process for {'account_name': 'testo', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr8tfBtTNQeCe4Vcro9jI\nG0WSMeI5D9Zn51A+cI3FEnxTq4ecs8nLri3eQHKZ6+dyzx+RdfF87e/hyHLyZOJf\nvrHUzOOfIH0ScwK7OmpG0JrpUo7F+9cfzj8JEBk96LZgvOWQGisNvyr17TvCVOuB\nkj3hE4GYvNhUPMrHLrcISZQO2Ahy77YMcl70p0xTlTWx0ysh0zyKDXN17scfn2lD\nqE6YP5tOqUcPgYmNTe0cDJQj7gmODxYchSRnZyD+J0J/mVeeaH9gLJmylgjbblMS\nlSUyda9d+Eajj06MLYGIBZKIjrg/SqHelKXTq7G8sSleO1AbhYXw3P4SGvuFNYC1\nNwIDAQAB\n-----END PUBLIC KEY-----'}
2021-11-15 17:54:17,887 DEBUG core.py Correct username, starting passwd check.
2021-11-15 17:54:17,889 DEBUG core.py Auth message = {'response': 511, 'bin': '49293cef1eac601f79de552b98678253da521c0643126ae5bed0a2ae574763c7f09db964c407faad9ea8b961e9e295a78ba3f7823444d985bc15ed8a566ff0e4'}
2021-11-15 17:54:17,892 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1372, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52534)>, {'response': 511, 'bin': '49293cef1eac601f79de552b98678253da521c0643126ae5bed0a2ae574763c7f09db964c407faad9ea8b961e9e295a78ba3f7823444d985bc15ed8a566ff0e4'}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:54:17,894 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1372, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52534)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:54:17,896 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1372, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52534)>, {'response': 200}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:54:18,506 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1372, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52534)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:54:18,506 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1636988057.8969605, 'account_name': 'testo'}
2021-11-15 17:54:18,516 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1372, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52534)>, {'response': 202, 'data_list': ['test1', 'test2', 'test3', 'Radif', 'Lui', 'testo', 'testo2']}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2021-11-15 17:54:19,017 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1372, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52534)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:54:19,017 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1636988058.6586905, 'user': 'testo'}
2021-11-15 17:54:19,023 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1372, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52534)>, {'response': 202, 'data_list': []}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2021-11-15 17:58:58,866 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1372, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52534)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:58:58,866 DEBUG core.py Разбор сообщения от клиента : {'action': 'add', 'time': 1636988338.7844138, 'user': 'testo', 'account_name': 'testo2'}
2021-11-15 17:58:59,505 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1372, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52534)>, {'response': 200}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2021-11-15 17:59:05,015 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1372, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52534)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:59:05,015 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1636988344.648475, 'account_name': 'testo2'}
2021-11-15 17:59:05,022 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1372, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52534)>, {'response': 400, 'error': 'Нет публичного ключа для данного пользователя'}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2021-11-15 17:59:24,857 INFO core.py Установлено соедение с ПК ('127.0.0.1', 55441)
2021-11-15 17:59:25,358 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1460, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 55441)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:59:25,358 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1636988364.8740895, 'user': {'account_name': 'testo2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsXAscVbw1yG/qLciWUtG\nAdGDDZjJVxtu/awf+slJwN7Kqag11MYX2kQ+loaGIwHyWaygFZtm1PhdaunnhFRx\nHV4kuJmnwIUTrygnZ+RnmuJtitGqzH7eKSRTFwNZqVvZgikLzafz4bsSKIj7S7vr\nlh3/P3m0gNTOjBreY7lFehdeOz0T7EmCODC85syOGnF6p1dQaM9xwQMjec9httfh\nrotTnGBQy17NJhxR6SlovAaJ6EDdLtbfp0v47FpIYe4vU/FEZCxI+t74kuubGVET\neG8vdkylNJR22mgehaGxvJrHJklTHEoWsjkA5bFkkXy/bS3FXGHpnH1z5yD6dZLJ\nLQIDAQAB\n-----END PUBLIC KEY-----'}}
2021-11-15 17:59:25,358 DEBUG core.py Start auth process for {'account_name': 'testo2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsXAscVbw1yG/qLciWUtG\nAdGDDZjJVxtu/awf+slJwN7Kqag11MYX2kQ+loaGIwHyWaygFZtm1PhdaunnhFRx\nHV4kuJmnwIUTrygnZ+RnmuJtitGqzH7eKSRTFwNZqVvZgikLzafz4bsSKIj7S7vr\nlh3/P3m0gNTOjBreY7lFehdeOz0T7EmCODC85syOGnF6p1dQaM9xwQMjec9httfh\nrotTnGBQy17NJhxR6SlovAaJ6EDdLtbfp0v47FpIYe4vU/FEZCxI+t74kuubGVET\neG8vdkylNJR22mgehaGxvJrHJklTHEoWsjkA5bFkkXy/bS3FXGHpnH1z5yD6dZLJ\nLQIDAQAB\n-----END PUBLIC KEY-----'}
2021-11-15 17:59:25,360 DEBUG core.py Correct username, starting passwd check.
2021-11-15 17:59:25,361 DEBUG core.py Auth message = {'response': 511, 'bin': '56b265f5bdf23742bde1a758ec159c9a1853b82b7409f1a37ea77cf21f0b4ca41c11fdf1bf08953fc8aadbf286c4cd49dba64bbc6754c856c7cd5904beb98d76'}
2021-11-15 17:59:25,363 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1460, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 55441)>, {'response': 511, 'bin': '56b265f5bdf23742bde1a758ec159c9a1853b82b7409f1a37ea77cf21f0b4ca41c11fdf1bf08953fc8aadbf286c4cd49dba64bbc6754c856c7cd5904beb98d76'}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:59:25,365 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1460, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 55441)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:59:25,367 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1460, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 55441)>, {'response': 200}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции autorize_user
2021-11-15 17:59:26,059 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1460, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 55441)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:59:26,059 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1636988365.3672004, 'account_name': 'testo2'}
2021-11-15 17:59:26,062 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1460, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 55441)>, {'response': 202, 'data_list': ['test1', 'test2', 'test3', 'Radif', 'Lui', 'testo', 'testo2']}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2021-11-15 17:59:26,565 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1460, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 55441)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:59:26,565 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1636988366.1751478, 'user': 'testo2'}
2021-11-15 17:59:26,574 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1460, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 55441)>, {'response': 202, 'data_list': []}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2021-11-15 17:59:34,584 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1372, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52534)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:59:34,584 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1636988374.4160323, 'account_name': 'testo2'}
2021-11-15 17:59:34,587 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1372, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52534)>, {'response': 511, 'bin': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsXAscVbw1yG/qLciWUtG\nAdGDDZjJVxtu/awf+slJwN7Kqag11MYX2kQ+loaGIwHyWaygFZtm1PhdaunnhFRx\nHV4kuJmnwIUTrygnZ+RnmuJtitGqzH7eKSRTFwNZqVvZgikLzafz4bsSKIj7S7vr\nlh3/P3m0gNTOjBreY7lFehdeOz0T7EmCODC85syOGnF6p1dQaM9xwQMjec9httfh\nrotTnGBQy17NJhxR6SlovAaJ6EDdLtbfp0v47FpIYe4vU/FEZCxI+t74kuubGVET\neG8vdkylNJR22mgehaGxvJrHJklTHEoWsjkA5bFkkXy/bS3FXGHpnH1z5yD6dZLJ\nLQIDAQAB\n-----END PUBLIC KEY-----'}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2021-11-15 17:59:40,597 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1372, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52534)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 17:59:40,597 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'testo', 'to': 'testo2', 'time': 1636988380.2496848, 'mess_text': 'WdUEFYNwU+e4/gX+waptNsv82lX9fNN4y/R6TWFenq1EtDnpSbdj9P7mF7Fawpstl72/uw7OAuYu9PvtCv2A5DPxugUPCeHaBnZDw3HzizGPqqU+2VqCAioI/9Rpt2CDAIgBj5w3MvBygF1hYPhEc+bsZSM6Wi+WJvYe3Raxn4H2JrSj+V3YQ8+fDuOpIpdB5aAPTkNuIOnIapStGZll+YMtbG0pcHVptWNaG5k8nKJWLeoSQXSM5tULqSDJlZ68wG4p/FukHrnSdz0z3B/+Xqn2XPvU1ottL89eY81iH9JzwQh2iH4AzP2pZ2XQ9q/12Jr0PvqiVIHiGYSp+yZROw=='}
2021-11-15 17:59:40,755 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1460, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 55441)>, {'action': 'message', 'from': 'testo', 'to': 'testo2', 'time': 1636988380.2496848, 'mess_text': 'WdUEFYNwU+e4/gX+waptNsv82lX9fNN4y/R6TWFenq1EtDnpSbdj9P7mF7Fawpstl72/uw7OAuYu9PvtCv2A5DPxugUPCeHaBnZDw3HzizGPqqU+2VqCAioI/9Rpt2CDAIgBj5w3MvBygF1hYPhEc+bsZSM6Wi+WJvYe3Raxn4H2JrSj+V3YQ8+fDuOpIpdB5aAPTkNuIOnIapStGZll+YMtbG0pcHVptWNaG5k8nKJWLeoSQXSM5tULqSDJlZ68wG4p/FukHrnSdz0z3B/+Xqn2XPvU1ottL89eY81iH9JzwQh2iH4AzP2pZ2XQ9q/12Jr0PvqiVIHiGYSp+yZROw=='}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции process_message
2021-11-15 17:59:40,755 INFO core.py Отправлено сообщение пользователю testo2 от пользователя testo.
2021-11-15 17:59:40,756 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1372, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52534)>, {'response': 200}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2021-11-15 18:01:30,866 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1460, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 55441)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 18:01:30,866 DEBUG core.py Разбор сообщения от клиента : {'action': 'add', 'time': 1636988490.3976219, 'user': 'testo2', 'account_name': 'testo'}
2021-11-15 18:01:31,078 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1460, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 55441)>, {'response': 200}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2021-11-15 18:01:32,583 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1460, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 55441)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 18:01:32,583 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1636988492.5702772, 'account_name': 'testo'}
2021-11-15 18:01:32,591 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1460, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 55441)>, {'response': 511, 'bin': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr8tfBtTNQeCe4Vcro9jI\nG0WSMeI5D9Zn51A+cI3FEnxTq4ecs8nLri3eQHKZ6+dyzx+RdfF87e/hyHLyZOJf\nvrHUzOOfIH0ScwK7OmpG0JrpUo7F+9cfzj8JEBk96LZgvOWQGisNvyr17TvCVOuB\nkj3hE4GYvNhUPMrHLrcISZQO2Ahy77YMcl70p0xTlTWx0ysh0zyKDXN17scfn2lD\nqE6YP5tOqUcPgYmNTe0cDJQj7gmODxYchSRnZyD+J0J/mVeeaH9gLJmylgjbblMS\nlSUyda9d+Eajj06MLYGIBZKIjrg/SqHelKXTq7G8sSleO1AbhYXw3P4SGvuFNYC1\nNwIDAQAB\n-----END PUBLIC KEY-----'}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2021-11-15 18:01:40,600 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1460, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 55441)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 18:01:40,601 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'testo2', 'to': 'testo', 'time': 1636988500.4094439, 'mess_text': 'TM6xDASB77YYR6qgA4F6rlL043UWZfByVC6H2N1RSoCyiBCECK3QQNJlKjRRkyz8kLZG6XBQtTEHLYcHVlIit/nCaRugiA4sLeeSxpwUh5RHtFUNenPkMY4MznZaCvxrAAS6oKtkBR/8tu1TcGQD3vfWJXhd4orySyzFT228XDeALtdQIxZhY3F/KZqSf6E3W2goNYRc0V6aY8eXGG/M8zjpM5c1PPdQOVSexzhOERN8D6+pQWOwvMd4Fbpagf6vhu3+h+3PBGvMJjInupr02v3v5JlXKtbqrn7thlHfVaubReiZRvOrWZFVlGWoQZrbuwkrinFUXdOBRLnYIuhHug=='}
2021-11-15 18:01:40,751 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1372, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52534)>, {'action': 'message', 'from': 'testo2', 'to': 'testo', 'time': 1636988500.4094439, 'mess_text': 'TM6xDASB77YYR6qgA4F6rlL043UWZfByVC6H2N1RSoCyiBCECK3QQNJlKjRRkyz8kLZG6XBQtTEHLYcHVlIit/nCaRugiA4sLeeSxpwUh5RHtFUNenPkMY4MznZaCvxrAAS6oKtkBR/8tu1TcGQD3vfWJXhd4orySyzFT228XDeALtdQIxZhY3F/KZqSf6E3W2goNYRc0V6aY8eXGG/M8zjpM5c1PPdQOVSexzhOERN8D6+pQWOwvMd4Fbpagf6vhu3+h+3PBGvMJjInupr02v3v5JlXKtbqrn7thlHfVaubReiZRvOrWZFVlGWoQZrbuwkrinFUXdOBRLnYIuhHug=='}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции process_message
2021-11-15 18:01:40,751 INFO core.py Отправлено сообщение пользователю testo от пользователя testo2.
2021-11-15 18:01:40,757 DEBUG core.py Была вызвана функция send_message c параметрами (<socket.socket fd=1460, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 55441)>, {'response': 200}), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции process_client_message
2021-11-15 18:01:47,766 DEBUG core.py Была вызвана функция get_message c параметрами (<socket.socket fd=1372, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 52534)>,), {}. Вызов из модуля common.utils.Вызов из функции self._bootstrap_inner().Вызов из функции run
2021-11-15 18:01:47,766 DEBUG core.py Разбор сообщения от клиента : {'action': 'add', 'time': 1636988507.6620958, 'user': 'testo', 'account_name': 'test1'}
